import = [
	"~/.config/alacritty/themes/themes/nordic.toml"
]

[font]
size = 16.0

[font.bold]
family = "SF Mono"
style = "Bold"

[font.bold_italic]
family = "SF Mono"
style = "Bold Italic"

[font.italic]
family = "SF Mono"
style = "Italic"

[font.normal]
family = "SF Mono"
style = "Regular"
